environments:
  dev:
    url: http://dev.bar.com
    name: Developer Setup
  prod:
    url: http://foo.bar.com
    name: My Cool App
server:
  port: 8881
---
spring:
  profiles: test
  server:
    port: 8882
---
spring:
  profiles: prod
  server:
      port: 8883

